name: Terraform Dev Deployment

on:
  workflow_dispatch:       # ðŸ‘ˆ Manual run allow karega
  pull_request:
    branches:
      - main
      - 'feature/*'        # ðŸ‘ˆ PRs from feature branches
  push:
    branches:
      - main
      - 'feature/*'        # ðŸ‘ˆ feature branches ke push pe bhi run hoga
    

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: [self-hosted, Windows, X64, chacha-runner]

    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 08c5d37a-4cbc-493e-95a4-cb555534e073
          tenant-id: de80a58f-1610-4908-a1a7-862be272a38c
          subscription-id: 0f48ce1f-16d2-42ba-8b4f-0bef1a58b563

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: ./enviroments/dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: ./enviroments/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./enviroments/dev       
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: ./enviroments/dev    
        
  terraform-apply:    
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ff27bcf6-f60c-4a57-8b01-8eee5de2a9cd
          tenant-id: 0f7010fd-209e-4344-8457-043ffb37143b
          subscription-id: 1075ec7a-b17a-4f37-bf3f-9d68c4506dc1   
          
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: environments/dev
